version: "3"

services:

  redis:
    image: redis:alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  mysql:
    platform: linux/x86_64
    container_name: mysql_db
    image: mysql:8.3.0
    ports:
      - "3308:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_as_ci --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: "@Manolo221212"
      MYSQL_USER: "juan_caste"
      MYSQL_PASSWORD: "@Manolo221212"
      MYSQL_DATABASE: "hexal_db"
    volumes:
      - ./data/mysql:/var/lib/mysql